/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlincinterop

fun main() {
    println("Java library path: ${System.getProperty("java.library.path")}") // Print the Java library path
    println("Loading NativeSample...")
    val test = NativeSample()
    println("NativeSample loaded successfully.")
    println("Calling sayHello()")
    test.sayHello()
    println("sayHello() called.")
}
